version: "3.8"

# networks:
#   jnp3:
#     driver: bridge

services:
  redis:
    image: redis
    container_name: redis
    expose:
      - 6379
  varnish-front:
    image: varnish:6
    ports:
      - 3000:80
    volumes:
      - ./varnish-front:/etc/varnish:ro
    depends_on:
      - jnp3-front1
      - jnp3-front2
  varnish-users:
    build: ./varnish-users/docker
    volumes:
      - ./varnish-users/config:/etc/varnish:ro
    expose:
      - 8000
    depends_on:
      - jnp3-users1
      - jnp3-users2
  jnp3-front1:
    # image: jnp3-front1
    # networks:
    #   - jnp3
    environment:
      - REDIS_URL=redis://redis
    build: ./front
    container_name: jnp3-front1
    # ports:
    #   - 3000:3000
    volumes:
      - ./front:/usr/src/front
    depends_on:
      - redis
  jnp3-front2:
    # image: jnp3-front
    # networks:
    #   - jnp3
    environment:
      - REDIS_URL=redis://redis
    build: ./front
    container_name: jnp3-front2
    # ports:
    #   - 3000:3000
    volumes:
      - ./front:/usr/src/front
    depends_on:
      - redis
  jnp3-users1:
    image: jnp3-users1
    # networks:
    #   - jnp3
    build: ./users
    container_name: jnp3-users1
    # ports:
    #   - 8000:8000
    volumes:
      - ./users:/usr/src/users
  jnp3-users2:
    image: jnp3-users2
    # networks:
    #   - jnp3
    build: ./users
    container_name: jnp3-users2
    # ports:
    #   - 8000:8000
    volumes:
      - ./users:/usr/src/users
  jnp3-posts:
    image: jnp3-posts
    # networks:
    #   - jnp3
    build: ./posts
    container_name: jnp3-posts
    ports:
      - 4000:4000
    volumes:
      - ./posts:/usr/src/posts
  jnp3-relations:
    image: jnp3-relations
    # networks:
    #   - jnp3
    build: ./relations
    container_name: jnp3-relations
    ports:
      - 5000:5000
    volumes:
      - ./relations:/usr/src/relations

